# ---------------------------------
# Arquivo: requirements.txt
# ---------------------------------
streamlit
moviepy


# ---------------------------------
# Arquivo: packages.txt
# ---------------------------------
ffmpeg


# ---------------------------------
# Arquivo: .streamlit/secrets.toml
# ---------------------------------
[credentials]
username = "luiz"
password = "Defecon4"

