# =================================
# Arquivo: .streamlit/secrets.toml
# =================================
# Para testes locais. No Streamlit Cloud, adicione nas configurações de "Secrets".
[credentials]
username = "luiz"
password = "Defecon4"
