# .streamlit/secrets.toml

[credentials]
[credentials.usernames]
jsmith = {email = "felipe123pvh@gmail.com", name = "Luiz Felipe", password = "$2b$12$longahashedpasswordhere1"}
rbriggs = {email = "rbriggs@gmail.com", name = "Rebecca Briggs", password = "$2b$12$anotherlonghashedpassword2"}

[cookie]
expiry_days = 30
key = "Defecon4" # Mude para qualquer string
name = "some_cookie_name"

[preauthorized]
emails = []
